In [1]:
import pandas as pd
import numpy as np

In [2]:
data1 = pd.Series(np.random.randn(9), index=[['a', 'a', 'a', 'b', 'b', 'c', 'c', 'd', 'd'], [1,2,3,1,3,1,2,2,3]])
data1.index

MultiIndex([('a', 1),
            ('a', 2),
            ('a', 3),
            ('b', 1),
            ('b', 3),
            ('c', 1),
            ('c', 2),
            ('d', 2),
            ('d', 3)],
           )

In [ ]:
data1

a  1   -1.148960
   2   -0.826461
   3    0.789299
b  1    0.545308
   3   -0.207185
c  1    0.733748
   2   -0.149006
d  2   -0.772600
   3    0.556717
dtype: float64

In [5]:
df = data1.unstack()
df

          1         2         3
a  1.681490 -0.627404 -0.407247
b  1.799451       NaN -0.783551
c -0.942733 -1.795357       NaN
d       NaN  1.494553 -1.335282

In [6]:
df.stack()

a  1    1.681490
   2   -0.627404
   3   -0.407247
b  1    1.799451
   3   -0.783551
c  1   -0.942733
   2   -1.795357
d  2    1.494553
   3   -1.335282
dtype: float64