In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("https://raw.githubusercontent.com/MansurCompAI/Practicum_Datasets/refs/heads/master/world_cities_air_water_quality.csv")
df

,City,"""Region""","""Country""","""AirQuality""","""WaterPollution"""
0,New York City,"""New York""","""United States of America""",46.816038,49.504950
1,"Washington, D.C.","""District of Columbia""","""United States of America""",66.129032,49.107143
2,San Francisco,"""California""","""United States of America""",60.514019,43.000000
3,Berlin,"""""","""Germany""",62.364130,28.612717
4,Los Angeles,"""California""","""United States of America""",36.621622,61.299435
...,...,...,...,...,...
3958,Yanbu,"""Medina Province""","""Saudi Arabia""",0.000000,50.000000
3959,Cordoba,"""Andalusia""","""Spain""",85.714286,8.333333
3960,Vic,"""Catalonia""","""Spain""",100.000000,0.000000
3961,Segovia,"""Castile and Leon""","""Spain""",100.000000,0.000000
3962,Zamora city,"""Castile and Leon""","""Spain""",100.000000,50.000000

In [8]:
df.columns = ['City', 'Region', 'Country', 'AirQuality', 'WaterPollution']
df

,City,Region,Country,AirQuality,WaterPollution
0,New York City,"""New York""","""United States of America""",46.816038,49.504950
1,"Washington, D.C.","""District of Columbia""","""United States of America""",66.129032,49.107143
2,San Francisco,"""California""","""United States of America""",60.514019,43.000000
3,Berlin,"""""","""Germany""",62.364130,28.612717
4,Los Angeles,"""California""","""United States of America""",36.621622,61.299435
...,...,...,...,...,...
3958,Yanbu,"""Medina Province""","""Saudi Arabia""",0.000000,50.000000
3959,Cordoba,"""Andalusia""","""Spain""",85.714286,8.333333
3960,Vic,"""Catalonia""","""Spain""",100.000000,0.000000
3961,Segovia,"""Castile and Leon""","""Spain""",100.000000,0.000000
3962,Zamora city,"""Castile and Leon""","""Spain""",100.000000,50.000000

In [11]:
df['Region'] = df['Region'].map(lambda x: x.replace('"', ''))
df

,City,Region,Country,AirQuality,WaterPollution
0,New York City,New York,"""United States of America""",46.816038,49.504950
1,"Washington, D.C.",District of Columbia,"""United States of America""",66.129032,49.107143
2,San Francisco,California,"""United States of America""",60.514019,43.000000
3,Berlin,,"""Germany""",62.364130,28.612717
4,Los Angeles,California,"""United States of America""",36.621622,61.299435
...,...,...,...,...,...
3958,Yanbu,Medina Province,"""Saudi Arabia""",0.000000,50.000000
3959,Cordoba,Andalusia,"""Spain""",85.714286,8.333333
3960,Vic,Catalonia,"""Spain""",100.000000,0.000000
3961,Segovia,Castile and Leon,"""Spain""",100.000000,0.000000
3962,Zamora city,Castile and Leon,"""Spain""",100.000000,50.000000

In [12]:
df['Country'] = df['Country'].map(lambda x: x.replace('"', ''))
df

,City,Region,Country,AirQuality,WaterPollution
0,New York City,New York,United States of America,46.816038,49.504950
1,"Washington, D.C.",District of Columbia,United States of America,66.129032,49.107143
2,San Francisco,California,United States of America,60.514019,43.000000
3,Berlin,,Germany,62.364130,28.612717
4,Los Angeles,California,United States of America,36.621622,61.299435
...,...,...,...,...,...
3958,Yanbu,Medina Province,Saudi Arabia,0.000000,50.000000
3959,Cordoba,Andalusia,Spain,85.714286,8.333333
3960,Vic,Catalonia,Spain,100.000000,0.000000
3961,Segovia,Castile and Leon,Spain,100.000000,0.000000
3962,Zamora city,Castile and Leon,Spain,100.000000,50.000000

In [13]:
df.stack()

0     City                          New York City
      Region                             New York
      Country            United States of America
      AirQuality                        46.816038
      WaterPollution                     49.50495
                                  ...
3962  City                            Zamora city
      Region                     Castile and Leon
      Country                               Spain
      AirQuality                            100.0
      WaterPollution                         50.0
Length: 19815, dtype: object

In [14]:
df[df['Country'] == 'Germany']

Empty DataFrame
Columns: [City, Region, Country, AirQuality, WaterPollution]
Index: []

In [15]:
df['Country'][2]

' United States of America'

In [17]:
df['Country'] = df['Country'].map(lambda x: x.strip())
df

,City,Region,Country,AirQuality,WaterPollution
0,New York City,New York,United States of America,46.816038,49.504950
1,"Washington, D.C.",District of Columbia,United States of America,66.129032,49.107143
2,San Francisco,California,United States of America,60.514019,43.000000
3,Berlin,,Germany,62.364130,28.612717
4,Los Angeles,California,United States of America,36.621622,61.299435
...,...,...,...,...,...
3958,Yanbu,Medina Province,Saudi Arabia,0.000000,50.000000
3959,Cordoba,Andalusia,Spain,85.714286,8.333333
3960,Vic,Catalonia,Spain,100.000000,0.000000
3961,Segovia,Castile and Leon,Spain,100.000000,0.000000
3962,Zamora city,Castile and Leon,Spain,100.000000,50.000000

In [19]:
df['Country'][2]

'United States of America'

In [21]:
df[df['Country']=='Uzbekistan']

        City Region     Country  AirQuality  WaterPollution
21  Tashkent         Uzbekistan   56.451613       49.166667

In [26]:
df[df['Country']=='Switzerland']['AirQuality'].value_counts()

AirQuality
100.000000    9
75.000000     5
91.666667     2
87.500000     2
92.857143     2
80.000000     2
94.318182     1
81.666667     1
71.538462     1
67.857143     1
71.666667     1
37.500000     1
78.260870     1
83.809524     1
96.875000     1
12.500000     1
62.500000     1
Name: count, dtype: int64

In [37]:
df1 = pd.pivot_table(df, index=['Country', 'City'], values=['AirQuality', 'WaterPollution'])
df1

                      AirQuality  WaterPollution
Country     City
Afghanistan Andkhoy    50.000000       50.000000
            Farah     100.000000        0.000000
            Herat      43.750000       31.250000
            Kabul      18.421053       81.060606
            Kandahar    0.000000       75.000000
...                          ...             ...
Zambia      Mansa      75.000000       25.000000
Zimbabwe    Bindura    50.000000       75.000000
            Bulawayo   67.857143       71.428571
            Harare     38.461538       87.500000
            Masvingo   25.000000       62.500000

[3895 rows x 2 columns]

In [35]:
df.index

RangeIndex(start=0, stop=3963, step=1)

In [36]:
df1.index

MultiIndex([('Afghanistan',        'Andkhoy'),
            ('Afghanistan',          'Farah'),
            ('Afghanistan',          'Herat'),
            ('Afghanistan',          'Kabul'),
            ('Afghanistan',       'Kandahar'),
            ('Afghanistan', 'Mazar-i-Sharif'),
            (    'Albania',         'Ballsh'),
            (    'Albania',         'Burrel'),
            (    'Albania',         'Durres'),
            (    'Albania',        'Elbasan'),
            ...
            (      'Yemen',          'Sanaa'),
            (      'Yemen',         'Ta'izz'),
            (     'Zambia',       'Chingola'),
            (     'Zambia',          'Kitwe'),
            (     'Zambia',         'Lusaka'),
            (     'Zambia',          'Mansa'),
            (   'Zimbabwe',        'Bindura'),
            (   'Zimbabwe',       'Bulawayo'),
            (   'Zimbabwe',         'Harare'),
            (   'Zimbabwe',       'Masvingo')],
           names=['Country', 'City'], length=3895)