In [1]:
import pandas as pd
import numpy as np

In [2]:
movies = pd.read_csv("https://raw.githubusercontent.com/MansurCompAI/Practicum_Datasets/refs/heads/master/IMDb/IMDb_movies.csv")
ratings = pd.read_csv("https://raw.githubusercontent.com/MansurCompAI/Practicum_Datasets/refs/heads/master/IMDb/IMDb_ratings.csv")
moveis_ratings = pd.merge(movies, ratings, on="imdb_title_id")

<ipython-input-2-144104179b08>:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  movies = pd.read_csv("https://raw.githubusercontent.com/MansurCompAI/Practicum_Datasets/refs/heads/master/IMDb/IMDb_movies.csv")

In [4]:
A = pd.DataFrame({'Transport': ['poezd', 'avtomobil', 'kema'],
                  'Tezligi': [70,180,45]})
A

   Transport  Tezligi
0      poezd       70
1  avtomobil      180
2       kema       45

In [8]:
B = pd.DataFrame({'Transport': ['poezd', 'avtomobil', 'tramvay'],
                  'Narxi': [98000, 10000, 65000]})
B

   Transport  Narxi
0      poezd  98000
1  avtomobil  10000
2    tramvay  65000

In [9]:
merged = pd.merge(A, B, on="Transport")
merged

   Transport  Tezligi  Narxi
0      poezd       70  98000
1  avtomobil      180  10000

In [10]:
merged_outer = pd.merge(A, B, how="outer")
merged_outer

   Transport  Tezligi    Narxi
0  avtomobil    180.0  10000.0
1       kema     45.0      NaN
2      poezd     70.0  98000.0
3    tramvay      NaN  65000.0

In [11]:
merged_left = pd.merge(A, B, how="left")
merged_left

   Transport  Tezligi    Narxi
0      poezd       70  98000.0
1  avtomobil      180  10000.0
2       kema       45      NaN

In [12]:
A = pd.DataFrame({'Transport_turi': ['poezd', 'avtomobil', 'kema'],
                  'Tezligi': [70,180,45]})
A.set_index("Transport_turi", inplace=True)
A

                Tezligi
Transport_turi
poezd                70
avtomobil           180
kema                 45

In [13]:
B

   Transport  Narxi
0      poezd  98000
1  avtomobil  10000
2    tramvay  65000

In [14]:
merged1 = pd.merge(A,B, left_index=True, right_on="Transport")
merged1

   Tezligi  Transport  Narxi
0       70      poezd  98000
1      180  avtomobil  10000