In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/MansurCompAI/Practicum_Datasets/refs/heads/master/data_pivot.csv')
df

                              date     item      value
0    1959-03-31 23:59:59.999999999  realgdp   2710.349
1    1959-03-31 23:59:59.999999999     infl      0.000
2    1959-03-31 23:59:59.999999999    unemp      5.800
3    1959-06-30 23:59:59.999999999  realgdp   2778.801
4    1959-06-30 23:59:59.999999999     infl      2.340
..                             ...      ...        ...
604  2009-06-30 23:59:59.999999999     infl      3.370
605  2009-06-30 23:59:59.999999999    unemp      9.200
606  2009-09-30 23:59:59.999999999  realgdp  12990.341
607  2009-09-30 23:59:59.999999999     infl      3.560
608  2009-09-30 23:59:59.999999999    unemp      9.600

[609 rows x 3 columns]

In [ ]:
pivoted_data = df.pivot(index='date', columns='item', values='value')
pivoted_data

item                           infl    realgdp  unemp
date
1959-03-31 23:59:59.999999999  0.00   2710.349    5.8
1959-06-30 23:59:59.999999999  2.34   2778.801    5.1
1959-09-30 23:59:59.999999999  2.74   2775.488    5.3
1959-12-31 23:59:59.999999999  0.27   2785.204    5.6
1960-03-31 23:59:59.999999999  2.31   2847.699    5.2
...                             ...        ...    ...
2008-09-30 23:59:59.999999999 -3.16  13324.600    6.0
2008-12-31 23:59:59.999999999 -8.79  13141.920    6.9
2009-03-31 23:59:59.999999999  0.94  12925.410    8.1
2009-06-30 23:59:59.999999999  3.37  12901.504    9.2
2009-09-30 23:59:59.999999999  3.56  12990.341    9.6

[203 rows x 3 columns]

In [8]:
df['value2'] = df['value'] ** 2
df

                              date     item      value        value2
0    1959-03-31 23:59:59.999999999  realgdp   2710.349  7.345992e+06
1    1959-03-31 23:59:59.999999999     infl      0.000  0.000000e+00
2    1959-03-31 23:59:59.999999999    unemp      5.800  3.364000e+01
3    1959-06-30 23:59:59.999999999  realgdp   2778.801  7.721735e+06
4    1959-06-30 23:59:59.999999999     infl      2.340  5.475600e+00
..                             ...      ...        ...           ...
604  2009-06-30 23:59:59.999999999     infl      3.370  1.135690e+01
605  2009-06-30 23:59:59.999999999    unemp      9.200  8.464000e+01
606  2009-09-30 23:59:59.999999999  realgdp  12990.341  1.687490e+08
607  2009-09-30 23:59:59.999999999     infl      3.560  1.267360e+01
608  2009-09-30 23:59:59.999999999    unemp      9.600  9.216000e+01

[609 rows x 4 columns]

In [11]:
pivoted_data1 = df.pivot(index='date', columns='item', values='value2')
pivoted_data1

item                              infl       realgdp  unemp
date
1959-03-31 23:59:59.999999999   0.0000  7.345992e+06  33.64
1959-06-30 23:59:59.999999999   5.4756  7.721735e+06  26.01
1959-09-30 23:59:59.999999999   7.5076  7.703334e+06  28.09
1959-12-31 23:59:59.999999999   0.0729  7.757361e+06  31.36
1960-03-31 23:59:59.999999999   5.3361  8.109390e+06  27.04
...                                ...           ...    ...
2008-09-30 23:59:59.999999999   9.9856  1.775450e+08  36.00
2008-12-31 23:59:59.999999999  77.2641  1.727101e+08  47.61
2009-03-31 23:59:59.999999999   0.8836  1.670662e+08  65.61
2009-06-30 23:59:59.999999999  11.3569  1.664488e+08  84.64
2009-09-30 23:59:59.999999999  12.6736  1.687490e+08  92.16

[203 rows x 3 columns]