In [1]:
import pandas as pd
import numpy as np

In [2]:
!wget = "https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/refs/heads/main/merc.csv"

--2025-04-12 17:26:54--  http://=/
Resolving = (=)... failed: Name or service not known.
wget: unable to resolve host address ‘=’
--2025-04-12 17:26:54--  https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/refs/heads/main/merc.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 728047 (711K) [text/plain]
Saving to: ‘merc.csv’

merc.csv            100%[===================>] 710.98K  --.-KB/s    in 0.06s

2025-04-12 17:26:54 (12.4 MB/s) - ‘merc.csv’ saved [728047/728047]

FINISHED --2025-04-12 17:26:54--
Total wall clock time: 0.3s
Downloaded: 1 files, 711K in 0.06s (12.4 MB/s)

In [3]:
!git clone "https://github.com/anvarnarz/praktikum_datasets"

Cloning into 'praktikum_datasets'...
remote: Enumerating objects: 145, done.
remote: Counting objects: 100% (52/52), done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 145 (delta 46), reused 44 (delta 43), pack-reused 93 (from 1)
Receiving objects: 100% (145/145), 9.72 MiB | 16.90 MiB/s, done.
Resolving deltas: 100% (53/53), done.

In [4]:
df = pd.read_excel("praktikum_datasets/uzbekistan.xlsx", names=['Hudud', 'Maydon', 'Aholi'])
df.head()

               Hudud  Maydon    Aholi
0   Andijon viloyati    4200  1899000
1    Buxoro viloyati   39400  1384700
2  Fargʻona viloyati    6800  2597000
3    Jizzax viloyati   20500   910500
4    Xorazm viloyati    6300  1200000

In [5]:
df.to_csv("uzbekistan.csv")

In [6]:
new_df = pd.read_csv("uzbekistan.csv")
new_df.head()

   Unnamed: 0              Hudud  Maydon    Aholi
0           0   Andijon viloyati    4200  1899000
1           1    Buxoro viloyati   39400  1384700
2           2  Fargʻona viloyati    6800  2597000
3           3    Jizzax viloyati   20500   910500
4           4    Xorazm viloyati    6300  1200000

In [7]:
obj = df.Maydon
obj

0       4200
1      39400
2       6800
3      20500
4       6300
5       7900
6     110800
7      28400
8     160000
9      16400
10      5100
11     20800
12     15300
Name: Maydon, dtype: int64

In [8]:
obj.to_csv("maydon.csv")

In [9]:
pd.read_csv("maydon.csv", index_col=0)

    Maydon
0     4200
1    39400
2     6800
3    20500
4     6300
5     7900
6   110800
7    28400
8   160000
9    16400
10    5100
11   20800
12   15300

In [10]:
pd.read_csv("maydon.csv", index_col=0).squeeze("columns")

0       4200
1      39400
2       6800
3      20500
4       6300
5       7900
6     110800
7      28400
8     160000
9      16400
10      5100
11     20800
12     15300
Name: Maydon, dtype: int64

In [11]:
df2 = pd.read_csv("praktikum_datasets/automobile_data.csv")
df2.head()

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
0,0,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,13495.0
1,1,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,16500.0
2,2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154,19,16500.0
3,3,audi,sedan,99.8,176.6,ohc,four,102,24,13950.0
4,4,audi,sedan,99.4,176.6,ohc,five,115,18,17450.0

In [12]:
df2.to_excel('new_cars.xlsx', index=False, columns=['company', 'body-style', 'price'])

In [13]:
pd.read_excel("new_cars.xlsx")

        company   body-style    price
0   alfa-romero  convertible  13495.0
1   alfa-romero  convertible  16500.0
2   alfa-romero    hatchback  16500.0
3          audi        sedan  13950.0
4          audi        sedan  17450.0
..          ...          ...      ...
56   volkswagen        sedan   7975.0
57   volkswagen        sedan   7995.0
58   volkswagen        sedan   9995.0
59        volvo        sedan  12940.0
60        volvo        wagon  13415.0

[61 rows x 3 columns]