In [4]:
import pandas as pd
import numpy as np
from pandas import Series

In [ ]:
obj = Series([1,2,3,4,5])
type(obj)

In [7]:
obj

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [8]:
obj.values

array([1, 2, 3, 4, 5])

In [9]:
obj.index

RangeIndex(start=0, stop=5, step=1)

In [10]:
obj[0]

np.int64(1)

In [11]:
obj2 = Series([1,2,3,4,5], index=['a', 'b', 'c', 'd', 'e'])
obj2

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [13]:
obj2.values

array([1, 2, 3, 4, 5])

In [14]:
obj2.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [15]:
obj2['a']

np.int64(1)

In [16]:
obj2[['a', 'd', 'c']]

a    1
d    4
c    3
dtype: int64

In [17]:
obj2[obj2>2]

c    3
d    4
e    5
dtype: int64

In [18]:
np.max(obj2)

5

In [19]:
np.sum(obj2)

np.int64(15)

In [22]:
np.exp(obj2)

a      2.718282
b      7.389056
c     20.085537
d     54.598150
e    148.413159
dtype: float64