In [1]:
import pandas as pd
from pandas import DataFrame, Series
import numpy as np

In [5]:
uz = {2020:33.5,2019:32.9,2018:32.5,2017:31.9,2016:31.4,2015:30.9}
kz = {2020:18.9,2019:18.5,2018:18.1,2017:17.7,2016:17.3,2015:16.9}
tj = {2020:11.9,2019:11.5,2018:11.1,2017:10.7,2016:10.3,2015:9.9}
kg = {2020:6.9,2019:6.5,2018:6.1,2017:5.7,2016:5.3,2015:4.9}
tr = {2020:6.4,2019:6.0,2018:5.6,2017:5.2,2016:4.8,2015:4.4}

df = DataFrame({'Uzbekistan':uz,'Kazakhstan':kz,'Tajikistan':tj,'Kyrgyzstan':kg,'Turkey':tr})
df

      Uzbekistan  Kazakhstan  Tajikistan  Kyrgyzstan  Turkey
2020        33.5        18.9        11.9         6.9     6.4
2019        32.9        18.5        11.5         6.5     6.0
2018        32.5        18.1        11.1         6.1     5.6
2017        31.9        17.7        10.7         5.7     5.2
2016        31.4        17.3        10.3         5.3     4.8
2015        30.9        16.9         9.9         4.9     4.4

In [10]:
df['Uzbekistan'].to_numpy()

array([33.5, 32.9, 32.5, 31.9, 31.4, 30.9])

In [11]:
df[['Uzbekistan', 'Tajikistan']]

      Uzbekistan  Tajikistan
2020        33.5        11.9
2019        32.9        11.5
2018        32.5        11.1
2017        31.9        10.7
2016        31.4        10.3
2015        30.9         9.9

In [12]:
df[3:]

      Uzbekistan  Kazakhstan  Tajikistan  Kyrgyzstan  Turkey
2017        31.9        17.7        10.7         5.7     5.2
2016        31.4        17.3        10.3         5.3     4.8
2015        30.9        16.9         9.9         4.9     4.4

In [16]:
df>10.

      Uzbekistan  Kazakhstan  Tajikistan  Kyrgyzstan  Turkey
2020        True        True        True       False   False
2019        True        True        True       False   False
2018        True        True        True       False   False
2017        True        True        True       False   False
2016        True        True        True       False   False
2015        True        True       False       False   False

In [18]:
df[['Uzbekistan']][df['Uzbekistan']>32]

      Uzbekistan
2020        33.5
2019        32.9
2018        32.5

In [19]:
df2 = df.transpose(copy=True)
df2

            2020  2019  2018  2017  2016  2015
Uzbekistan  33.5  32.9  32.5  31.9  31.4  30.9
Kazakhstan  18.9  18.5  18.1  17.7  17.3  16.9
Tajikistan  11.9  11.5  11.1  10.7  10.3   9.9
Kyrgyzstan   6.9   6.5   6.1   5.7   5.3   4.9
Turkey       6.4   6.0   5.6   5.2   4.8   4.4