In [1]:
import pandas as pd
from pandas import DataFrame, Series
import numpy as np

In [2]:
uz = {2020:33.5,2019:32.9,2018:32.5,2017:31.9,2016:31.4,2015:30.9}
kz = {2020:18.9,2019:18.5,2018:18.1,2017:17.7,2016:17.3,2015:16.9}
tj = {2020:11.9,2019:11.5,2018:11.1,2017:10.7,2016:10.3,2015:9.9}
kg = {2020:6.9,2019:6.5,2018:6.1,2017:5.7,2016:5.3,2015:4.9}
tr = {2020:6.4,2019:6.0,2018:5.6,2017:5.2,2016:4.8,2015:4.4}

df = DataFrame({'Uzbekistan':uz,'Kazakhstan':kz,'Tajikistan':tj,'Kyrgyzstan':kg,'Turkey':tr})
df

      Uzbekistan  Kazakhstan  Tajikistan  Kyrgyzstan  Turkey
2020        33.5        18.9        11.9         6.9     6.4
2019        32.9        18.5        11.5         6.5     6.0
2018        32.5        18.1        11.1         6.1     5.6
2017        31.9        17.7        10.7         5.7     5.2
2016        31.4        17.3        10.3         5.3     4.8
2015        30.9        16.9         9.9         4.9     4.4

In [9]:
df.loc[[2017, 2015],['Uzbekistan', 'Tajikistan']]

      Uzbekistan  Tajikistan
2017        31.9        10.7
2015        30.9         9.9

In [10]:
df.iloc[[0,4],[1,4]]

      Kazakhstan  Turkey
2020        18.9     6.4
2016        17.3     4.8

In [12]:
df.at[2015,'Uzbekistan']

np.float64(30.9)

In [14]:
df.iat[0,2]

np.float64(11.9)

In [16]:
nums = list(range(10,21))
nums

[10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [17]:
nums[0]

10

In [18]:
nums[-1]

20

In [20]:
nums = pd.Series(np.arange(10.))
nums

0    0.0
1    1.0
2    2.0
3    3.0
4    4.0
5    5.0
6    6.0
7    7.0
8    8.0
9    9.0
dtype: float64

In [21]:
nums[0]

np.float64(0.0)

In [22]:
nums[-1]

KeyError: -1

In [28]:
ser = Series(np.arange(5.),index=['a','b','c','d','e'])
ser

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [27]:
ser['a']

np.float64(0.0)

In [29]:
ser.iloc[-1]

np.float64(4.0)