In [5]:
import pandas as pd
from pandas import DataFrame, Series
import numpy as np

In [3]:
s1 = Series([7.3, -2.5, 3.4, 1.5], index=['a','c', 'd', 'e'])
s2 = Series([-2.1, 3.6, -1.5, 4, 3.1], index=['a','c', 'e', 'f', 'g'])

In [4]:
s1+s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [7]:
df1 = DataFrame(np.arange(9).reshape(3,3), columns=list('bcd'), index=['Ohio', 'Texas', 'Colorado'])
df2 = DataFrame(np.arange(12).reshape(4,3), columns=list('bde'), index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [9]:
df2

        b   d   e
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11

In [10]:
df1+df2

            b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [11]:
df1.add(df2)

            b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [13]:
df1.add(df2, fill_value=1)

             b    c     d     e
Colorado   7.0  8.0   9.0   NaN
Ohio       3.0  2.0   6.0   6.0
Oregon    10.0  NaN  11.0  12.0
Texas      9.0  5.0  12.0   9.0
Utah       1.0  NaN   2.0   3.0

In [14]:
df1.div(df2, fill_value=1)

                 b    c         d         e
Colorado  6.000000  7.0  8.000000       NaN
Ohio      0.000000  1.0  0.500000  0.200000
Oregon    0.111111  NaN  0.100000  0.090909
Texas     0.500000  4.0  0.714286  0.125000
Utah           inf  NaN  1.000000  0.500000

In [15]:
df1.sub(df2)

            b   c    d   e
Colorado  NaN NaN  NaN NaN
Ohio     -3.0 NaN -2.0 NaN
Oregon    NaN NaN  NaN NaN
Texas    -3.0 NaN -2.0 NaN
Utah      NaN NaN  NaN NaN

In [17]:
df = DataFrame(np.arange(1,13).reshape(3,4), index=list('acd'), columns=['one', 'two', 'three', 'four'])
sr = Series(np.arange(4), index=df.columns)

In [18]:
df

   one  two  three  four
a    1    2      3     4
c    5    6      7     8
d    9   10     11    12

In [19]:
sr

one      0
two      1
three    2
four     3
dtype: int64

In [20]:
df+sr

   one  two  three  four
a    1    3      5     7
c    5    7      9    11
d    9   11     13    15

In [21]:
df.sub(sr)

   one  two  three  four
a    1    1      1     1
c    5    5      5     5
d    9    9      9     9

In [22]:
df

   one  two  three  four
a    1    2      3     4
c    5    6      7     8
d    9   10     11    12

In [23]:
sr

one      0
two      1
three    2
four     3
dtype: int64

In [24]:
df+sr['three']

   one  two  three  four
a    3    4      5     6
c    7    8      9    10
d   11   12     13    14