In [1]:
import pandas as pd
from pandas import DataFrame, Series
import numpy as np

In [3]:
df = DataFrame(np.random.randn(4, 3), columns=list('bde'), index=['Utah', 'Ohio', 'Texas', 'Oregon'])
df

               b         d         e
Utah    0.017860  0.124196 -1.611274
Ohio    1.482791  0.811451 -0.059473
Texas   1.427935 -0.095828  0.774072
Oregon  0.452048 -1.216729  1.231777

In [5]:
np.abs(df)

               b         d         e
Utah    0.017860  0.124196  1.611274
Ohio    1.482791  0.811451  0.059473
Texas   1.427935  0.095828  0.774072
Oregon  0.452048  1.216729  1.231777

In [11]:
f = lambda x: x.max() - x.min()
df.apply(f)

b    1.464931
d    2.028180
e    2.843052
dtype: float64

In [12]:
def foo(x):
    return Series([x.min(), x.max()], index=['min', 'max'])
df.apply(foo)

            b         d         e
min  0.017860 -1.216729 -1.611274
max  1.482791  0.811451  1.231777

In [13]:
df = DataFrame(np.arange(1,13).reshape(3,4), index=list('abc'), columns=['Utah', 'Ohio', 'Texas', 'Oregon'])
df

   Utah  Ohio  Texas  Oregon
a     1     2      3       4
b     5     6      7       8
c     9    10     11      12

In [16]:
df.map(lambda x: x*x)

   Utah  Ohio  Texas  Oregon
a     1     4      9      16
b    25    36     49      64
c    81   100    121     144