In [1]:
import pandas as pd
from pandas import Series
import numpy as np

In [12]:
cars = {
    "Honda Civic": 22000,
    "Toyota Corolla": 25000,
    "Ford Focus": 27000,
    "Audi A4": 35000,
    "Audi A8": 45000
}
car = Series(cars)
car

Honda Civic       22000
Toyota Corolla    25000
Ford Focus        27000
Audi A4           35000
Audi A8           45000
dtype: int64

In [16]:
models = ["Honda Civic", "Toyota Corolla","BMW", "Ford Focus", "Audi A4", "Audi A8"]
car1 = Series(cars, index=models)
car1

Honda Civic       22000.0
Toyota Corolla    25000.0
BMW                   NaN
Ford Focus        27000.0
Audi A4           35000.0
Audi A8           45000.0
dtype: float64

In [17]:
car1.isnull()

Honda Civic       False
Toyota Corolla    False
BMW                True
Ford Focus        False
Audi A4           False
Audi A8           False
dtype: bool

In [18]:
car1.notnull()

Honda Civic        True
Toyota Corolla     True
BMW               False
Ford Focus         True
Audi A4            True
Audi A8            True
dtype: bool

In [19]:
car1+car

Audi A4           70000.0
Audi A8           90000.0
BMW                   NaN
Ford Focus        54000.0
Honda Civic       44000.0
Toyota Corolla    50000.0
dtype: float64

In [20]:
car1.name = "Car Prices"
car1.index.name = "Car Models"
car1

Car Models
Honda Civic       22000.0
Toyota Corolla    25000.0
BMW                   NaN
Ford Focus        27000.0
Audi A4           35000.0
Audi A8           45000.0
Name: Car Prices, dtype: float64