In [2]:
import pandas as pd
from pandas import DataFrame

In [6]:
data = {
    'Yil': [2021, 2020, 2019, 2018, 2017, 2016, 2015, 2010],
    'Aholi soni': [33.9, 33.5, 32.9, 32.5, 31.9, 31.4, 30.9, 28.5],
    'Temp': [1.54, 1.44, 1.33, 1.21, 1.02, 0.87, 0.8, 1.53]
}
df = DataFrame(data)
df

    Yil  Aholi soni  Temp
0  2021        33.9  1.54
1  2020        33.5  1.44
2  2019        32.9  1.33
3  2018        32.5  1.21
4  2017        31.9  1.02
5  2016        31.4  0.87
6  2015        30.9  0.80
7  2010        28.5  1.53

In [10]:
df.head()

    Yil  Aholi soni  Temp
0  2021        33.9  1.54
1  2020        33.5  1.44
2  2019        32.9  1.33
3  2018        32.5  1.21
4  2017        31.9  1.02

In [11]:
df.shape

(8, 3)