In [17]:
import pandas as pd
from pandas import DataFrame

In [18]:
data = {
    'Yil': [2021, 2020, 2019, 2018, 2017, 2016, 2015, 2010],
    'Aholi soni': [33.9, 33.5, 32.9, 32.5, 31.9, 31.4, 30.9, 28.5],
    'Temp': [1.54, 1.44, 1.33, 1.21, 1.02, 0.87, 0.8, 1.53]
}
df = DataFrame(data)
df

    Yil  Aholi soni  Temp
0  2021        33.9  1.54
1  2020        33.5  1.44
2  2019        32.9  1.33
3  2018        32.5  1.21
4  2017        31.9  1.02
5  2016        31.4  0.87
6  2015        30.9  0.80
7  2010        28.5  1.53

In [19]:
df = DataFrame(data, columns=['Yil', 'Temp', 'Aholi soni', 'YIM'])
df

    Yil  Temp  Aholi soni  YIM
0  2021  1.54        33.9  NaN
1  2020  1.44        33.5  NaN
2  2019  1.33        32.9  NaN
3  2018  1.21        32.5  NaN
4  2017  1.02        31.9  NaN
5  2016  0.87        31.4  NaN
6  2015  0.80        30.9  NaN
7  2010  1.53        28.5  NaN

In [20]:
df = DataFrame(data, columns=['Yil', 'Temp', 'Aholi soni', 'YIM'])
df

    Yil  Temp  Aholi soni  YIM
0  2021  1.54        33.9  NaN
1  2020  1.44        33.5  NaN
2  2019  1.33        32.9  NaN
3  2018  1.21        32.5  NaN
4  2017  1.02        31.9  NaN
5  2016  0.87        31.4  NaN
6  2015  0.80        30.9  NaN
7  2010  1.53        28.5  NaN

In [26]:
df = DataFrame(data, columns=['Yil', 'Temp', 'Aholi soni', 'YIM'], index=[21,20,19,18,17,16,15,14])
df

     Yil  Temp  Aholi soni  YIM
21  2021  1.54        33.9  NaN
20  2020  1.44        33.5  NaN
19  2019  1.33        32.9  NaN
18  2018  1.21        32.5  NaN
17  2017  1.02        31.9  NaN
16  2016  0.87        31.4  NaN
15  2015  0.80        30.9  NaN
14  2010  1.53        28.5  NaN

In [22]:
yil = df['Yil']
yil

21    2021
20    2020
19    2019
18    2018
17    2017
16    2016
15    2015
14    2010
Name: Yil, dtype: int64

In [23]:
type(yil)

pandas.core.series.Series

In [24]:
df.Temp

21    1.54
20    1.44
19    1.33
18    1.21
17    1.02
16    0.87
15    0.80
14    1.53
Name: Temp, dtype: float64

In [27]:
df

     Yil  Temp  Aholi soni  YIM
21  2021  1.54        33.9  NaN
20  2020  1.44        33.5  NaN
19  2019  1.33        32.9  NaN
18  2018  1.21        32.5  NaN
17  2017  1.02        31.9  NaN
16  2016  0.87        31.4  NaN
15  2015  0.80        30.9  NaN
14  2010  1.53        28.5  NaN

In [29]:
df.YIM = 0
df

     Yil  Temp  Aholi soni  YIM
21  2021  1.54        33.9    0
20  2020  1.44        33.5    0
19  2019  1.33        32.9    0
18  2018  1.21        32.5    0
17  2017  1.02        31.9    0
16  2016  0.87        31.4    0
15  2015  0.80        30.9    0
14  2010  1.53        28.5    0

In [30]:
val = pd.Series([17, 18, 20], index=[21, 20, 19])
df.YIM = val
df

     Yil  Temp  Aholi soni   YIM
21  2021  1.54        33.9  17.0
20  2020  1.44        33.5  18.0
19  2019  1.33        32.9  20.0
18  2018  1.21        32.5   NaN
17  2017  1.02        31.9   NaN
16  2016  0.87        31.4   NaN
15  2015  0.80        30.9   NaN
14  2010  1.53        28.5   NaN

In [31]:
df['1+'] = df.Temp > 1
df

     Yil  Temp  Aholi soni   YIM     1+
21  2021  1.54        33.9  17.0   True
20  2020  1.44        33.5  18.0   True
19  2019  1.33        32.9  20.0   True
18  2018  1.21        32.5   NaN   True
17  2017  1.02        31.9   NaN   True
16  2016  0.87        31.4   NaN  False
15  2015  0.80        30.9   NaN  False
14  2010  1.53        28.5   NaN   True

In [32]:
del df['1+']
df

     Yil  Temp  Aholi soni   YIM
21  2021  1.54        33.9  17.0
20  2020  1.44        33.5  18.0
19  2019  1.33        32.9  20.0
18  2018  1.21        32.5   NaN
17  2017  1.02        31.9   NaN
16  2016  0.87        31.4   NaN
15  2015  0.80        30.9   NaN
14  2010  1.53        28.5   NaN