In [3]:
import pandas as pd
from pandas import DataFrame

In [4]:
data = {
    "O'zbekiston": {2021:33.9, 2020:33.5, 2019:33.0, 2018:32.4, 2017:36.5},
    "Kazakhstan": {2021:18.9, 2020:18.7, 2019:18.5, 2018:18.3, 2017:18.1, 2016:17.8}
}
df = pd.DataFrame(data)
df

      O'zbekiston  Kazakhstan
2021         33.9        18.9
2020         33.5        18.7
2019         33.0        18.5
2018         32.4        18.3
2017         36.5        18.1
2016          NaN        17.8

In [5]:
df.index.name = "Yil"
df

      O'zbekiston  Kazakhstan
Yil
2021         33.9        18.9
2020         33.5        18.7
2019         33.0        18.5
2018         32.4        18.3
2017         36.5        18.1
2016          NaN        17.8

In [6]:
df2 = pd.DataFrame(data, index=[2021, 2020, 2016])
df2

      O'zbekiston  Kazakhstan
2021         33.9        18.9
2020         33.5        18.7
2016          NaN        17.8

In [7]:
df2.T
df2

      O'zbekiston  Kazakhstan
2021         33.9        18.9
2020         33.5        18.7
2016          NaN        17.8

In [8]:
df2.values

array([[33.9, 18.9],
       [33.5, 18.7],
       [ nan, 17.8]])