In [13]:
import pandas as pd
from pandas import DataFrame

In [14]:
data = {
    'Yil': [2021,2020,2019,2018,2017,2016,2015,2010],
    'Aholi soni': [33.9, 33.5, 32.9, 32.5, 31.9, 31.4, 30.9, 28.5],
    'Temp': [1.54, 1.48, 1.56, 1.62, 1.65, 1.66, 1.64, 1.53],
    'Zichlik': [79.77, 78.68, 77.53, 76.34, 75.13, 73.91, 72.71, 67.03]
}
df = DataFrame(data)
df

    Yil  Aholi soni  Temp  Zichlik
0  2021        33.9  1.54    79.77
1  2020        33.5  1.48    78.68
2  2019        32.9  1.56    77.53
3  2018        32.5  1.62    76.34
4  2017        31.9  1.65    75.13
5  2016        31.4  1.66    73.91
6  2015        30.9  1.64    72.71
7  2010        28.5  1.53    67.03

In [15]:
df.index = [21,20,19,18,17,16,15,10]
df

     Yil  Aholi soni  Temp  Zichlik
21  2021        33.9  1.54    79.77
20  2020        33.5  1.48    78.68
19  2019        32.9  1.56    77.53
18  2018        32.5  1.62    76.34
17  2017        31.9  1.65    75.13
16  2016        31.4  1.66    73.91
15  2015        30.9  1.64    72.71
10  2010        28.5  1.53    67.03

In [20]:
ind = [21,20,19,18,17,16,15,10]
ind.sort()
ind

[10, 15, 16, 17, 18, 19, 20, 21]

In [22]:
df.reindex(ind)

     Yil  Aholi soni  Temp  Zichlik
10  2010        28.5  1.53    67.03
15  2015        30.9  1.64    72.71
16  2016        31.4  1.66    73.91
17  2017        31.9  1.65    75.13
18  2018        32.5  1.62    76.34
19  2019        32.9  1.56    77.53
20  2020        33.5  1.48    78.68
21  2021        33.9  1.54    79.77

In [23]:
df

     Yil  Aholi soni  Temp  Zichlik
21  2021        33.9  1.54    79.77
20  2020        33.5  1.48    78.68
19  2019        32.9  1.56    77.53
18  2018        32.5  1.62    76.34
17  2017        31.9  1.65    75.13
16  2016        31.4  1.66    73.91
15  2015        30.9  1.64    72.71
10  2010        28.5  1.53    67.03

In [25]:
df = df.reindex(ind)
df

     Yil  Aholi soni  Temp  Zichlik
10  2010        28.5  1.53    67.03
15  2015        30.9  1.64    72.71
16  2016        31.4  1.66    73.91
17  2017        31.9  1.65    75.13
18  2018        32.5  1.62    76.34
19  2019        32.9  1.56    77.53
20  2020        33.5  1.48    78.68
21  2021        33.9  1.54    79.77

In [26]:
df.reindex([10,15,20])

     Yil  Aholi soni  Temp  Zichlik
10  2010        28.5  1.53    67.03
15  2015        30.9  1.64    72.71
20  2020        33.5  1.48    78.68

In [28]:
df.reindex(index=range(10,22), method='nearest')

     Yil  Aholi soni  Temp  Zichlik
10  2010        28.5  1.53    67.03
11  2010        28.5  1.53    67.03
12  2010        28.5  1.53    67.03
13  2015        30.9  1.64    72.71
14  2015        30.9  1.64    72.71
15  2015        30.9  1.64    72.71
16  2016        31.4  1.66    73.91
17  2017        31.9  1.65    75.13
18  2018        32.5  1.62    76.34
19  2019        32.9  1.56    77.53
20  2020        33.5  1.48    78.68
21  2021        33.9  1.54    79.77

In [34]:
df.reindex(index=range(10,22),columns=['Aholi soni', 'Temp', 'Zichlik']).sample()

    Aholi soni  Temp  Zichlik
13         NaN   NaN      NaN

In [35]:
df.loc[[10,15,20],['Aholi soni', 'Temp', 'Zichlik']]

    Aholi soni  Temp  Zichlik
10        28.5  1.53    67.03
15        30.9  1.64    72.71
20        33.5  1.48    78.68