In [2]:
import pandas as pd
from pandas import DataFrame

In [3]:
data = {
    'Yil': [2021,2020,2019,2018,2017,2016,2015,2010],
    'Aholi soni': [33.9, 33.5, 32.9, 32.5, 31.9, 31.4, 30.9, 28.5],
    'Temp': [1.54, 1.48, 1.56, 1.62, 1.65, 1.66, 1.64, 1.53],
    'Zichlik': [79.77, 78.68, 77.53, 76.34, 75.13, 73.91, 72.71, 67.03]
}
df = DataFrame(data)
df

    Yil  Aholi soni  Temp  Zichlik
0  2021        33.9  1.54    79.77
1  2020        33.5  1.48    78.68
2  2019        32.9  1.56    77.53
3  2018        32.5  1.62    76.34
4  2017        31.9  1.65    75.13
5  2016        31.4  1.66    73.91
6  2015        30.9  1.64    72.71
7  2010        28.5  1.53    67.03

In [7]:
arr = range(10,21)
df = df.reindex(arr)
df

    Yil  Aholi soni  Temp  Zichlik
10  NaN         NaN   NaN      NaN
11  NaN         NaN   NaN      NaN
12  NaN         NaN   NaN      NaN
13  NaN         NaN   NaN      NaN
14  NaN         NaN   NaN      NaN
15  NaN         NaN   NaN      NaN
16  NaN         NaN   NaN      NaN
17  NaN         NaN   NaN      NaN
18  NaN         NaN   NaN      NaN
19  NaN         NaN   NaN      NaN
20  NaN         NaN   NaN      NaN

In [12]:
df2  = df.drop([10,15])
df2

    Yil  Aholi soni  Temp  Zichlik
11  NaN         NaN   NaN      NaN
12  NaN         NaN   NaN      NaN
13  NaN         NaN   NaN      NaN
14  NaN         NaN   NaN      NaN
16  NaN         NaN   NaN      NaN
17  NaN         NaN   NaN      NaN
18  NaN         NaN   NaN      NaN
19  NaN         NaN   NaN      NaN
20  NaN         NaN   NaN      NaN

In [13]:
df2 = df2.drop('Yil', axis='columns')
df2

    Aholi soni  Temp  Zichlik
11         NaN   NaN      NaN
12         NaN   NaN      NaN
13         NaN   NaN      NaN
14         NaN   NaN      NaN
16         NaN   NaN      NaN
17         NaN   NaN      NaN
18         NaN   NaN      NaN
19         NaN   NaN      NaN
20         NaN   NaN      NaN