![Imgur](https://i.imgur.com/5pXzCIu.png)

# Data Science va Sun'iy Intellekt Praktikum

## Ma'lumotlar tahlili. Pandas kutubxonasi.

### PANDAS. Yakuniy vazifa. **1-QISM**

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/world_population.csv", index_col=0)

### 1-VAZIFA. Yuqoridagi DF ustunlari nomini quyidagi qiymatlarga o'zgartiring va DF yuqorisidan 3 ta davlatni chiqaring
`['davlat','zichlik_km','zichlik_mi','aholi','maydoni']`

In [ ]:
# JAVOBNI SHUYERGA YOZING

In [ ]:
#@title To'g'ri javob
df.columns = ['davlat','zichlik_km','zichlik_mi','aholi','maydoni']
df.head(3)

         davlat  zichlik_km  zichlik_mi     aholi  maydoni
rank
1         Macau  21946.4667  56841.3487   658.394       30
2        Monaco  19755.5000  51166.7450    39.511        2
3     Singapore   8305.1915  21510.4461  5896.686      710

## Yuqoridagi jadval dunyo davlatlarining aholi zichligi bo'yicha reytingini ko'rsatadi.
DF indeksi sifatida davlatning zichlik reytingi olingan (aholi eng zich yashaydigan davlatlar yuqorida).

**Ustunlar:**

`davlat` - Davlat nomi

`zichlik_km` - har 1 kv.km. ga to'g'ri keluvchi aholi soni

`zichlik_mi` - har 1 kv.milyaga to'g'ri keluvchi aholi soni (milya - AQSh masofa o'lchov birligi)

`aholi` - 2021-yilga ko'rsa aholi soni (ming)

`maydoni` - davlat maydoni (kv.km)

### 2-VAZIFA. DF oxiridan 10 ta qator chiqaring.

In [ ]:
# JAVOBNI SHUYERGA YOZING

### 3-VAZIFA. DF dan 10, 20, 100, 200-indekslarda turgan davlatlarni alohida DF ko'rinishida chiqaring.

In [ ]:
# JAVOBNI SHUYERGA YOZING

### 4-VAZIFA. Davlatlar orasida `Uzbekistan`, `Hong-Kong`, `Antartica` borligini tekshiring

In [ ]:
# JAVOBNI SHUYERGA YOZING

### 5-VAZIFA.
#### 5.1 DFning `davlat` nomli ustunini uning indeksi qilib belgilang.
#### 5.2 `davlat` ustunini tashlab yuboring.
#### 5.3 DFni davlat nomi bo'yicha tartiblang

In [ ]:
# JAVOBNI SHUYERGA YOZING

In [ ]:
#@title Kutilayotgan natija

                zichlik_km  zichlik_mi      aholi  maydoni
davlat
Afghanistan        61.0757    158.1862  39835.428   652230
Albania            99.9351    258.8318   2872.933    28748
Algeria            18.7328     48.5179  44616.624  2381741
American Samoa    276.8844    717.1307     55.100      199
Andorra           165.2885    428.0971     77.355      468

### 6-VAZIFA. DF dan `Uzbekistan`, `Malaysia`, `South Korea`, `France` davlatlari `aholi` va `maydoni` ustunlari bilan alohida DF ko'rinishida ajratib oling.

In [ ]:
# JAVOBNI SHUYERGA YOZING

In [ ]:
#@title O'xshash natija (boshqa davlatlar uchun)

                 aholi  maydoni
davlat
Singapore     5896.686      710
North Korea  25887.041   120538
Germany      83900.473   357114
Kazakhstan   18994.962  2724900

### 7-VAZIFA. Asl DFning `aholi` ustuni qiymatlarini 1000 ga ko'paytiring.

In [ ]:
# JAVOBNI SHUYERGA YOZING

In [ ]:
#@title Kutilgan natija

                zichlik_km  zichlik_mi       aholi  maydoni
davlat
Afghanistan        61.0757    158.1862  39835428.0   652230
Albania            99.9351    258.8318   2872933.0    28748
Algeria            18.7328     48.5179  44616624.0  2381741
American Samoa    276.8844    717.1307     55100.0      199
Andorra           165.2885    428.0971     77355.0      468

DF ni `aholi` ustuni bo'yicha kamayish tartibida tahlang va aholisi eng kam 10 ta davlatni chiqaring.

In [ ]:
# JAVOBNI SHUYERGA YOZING

### 8-VAZIFA. DFni `maydoni` bo'yicha reytinglang (rank) va reytinglarni yangi `rank` ustuniga yozing.

In [ ]:
# JAVOBNI SHUYERGA YOZING

In [ ]:
#@title Kutilgan natija

                   zichlik_km  zichlik_mi       aholi  maydoni   rank
davlat
Afghanistan           61.0757    158.1862  39835428.0   652230  192.0
Albania               99.9351    258.8318   2872933.0    28748   89.0
Algeria               18.7328     48.5179  44616624.0  2381741  223.0
American Samoa       276.8844    717.1307     55100.0      199   20.0
Andorra              165.2885    428.0971     77355.0      468   38.0
...                       ...         ...         ...      ...    ...
Wallis and Futuna     78.1268    202.3483     11094.0      142   15.0
Western Sahara         2.3003      5.9577    611875.0   266000  155.0
Yemen                 57.7509    149.5749  30490640.0   527968  183.0
Zambia                25.1400     65.1125  18920651.0   752612  194.0
Zimbabwe              38.6229    100.0333  15092171.0   390757  172.0

[232 rows x 5 columns]

#### `Uzbekistan`, `United Kingdom`, `Indonesia` davlatlari alohida df ko'rinishida chiqaring

In [ ]:
# JAVOBNI SHUYERGA YOZING

In [ ]:
#@title O'xshash natija (boshqa davlatlar uchun)

               zichlik_km  zichlik_mi        aholi  maydoni   rank
davlat
Turkmenistan      12.5342     32.4635    6117924.0   488100  180.0
United States     35.5200     91.9968  332915073.0  9372610  229.0
Vietnam          296.3927    767.6572   98168833.0   331212  166.0

### 9-VAZIFA. DFni `davlat` nomi bo'yicha tartiblang.

In [ ]:
# JAVOBNI SHUYERGA YOZING

In [ ]:
#@title Kutilgan natija

                zichlik_km  zichlik_mi       aholi  maydoni   rank
davlat
Afghanistan        61.0757    158.1862  39835428.0   652230  192.0
Albania            99.9351    258.8318   2872933.0    28748   89.0
Algeria            18.7328     48.5179  44616624.0  2381741  223.0
American Samoa    276.8844    717.1307     55100.0      199   20.0
Andorra           165.2885    428.0971     77355.0      468   38.0

#### DFdan 10,50,100,200-o'rinda turgan davlatlarni alohida DF ko'rinishida chiqaring

In [ ]:
# JAVOBNI SHUYERGA YOZING

In [ ]:
#@title O'xshash natija (boshqa qatorlar uchun)

                              zichlik_km  zichlik_mi     aholi  maydoni  rank
davlat
Belize                           17.6310     45.6643  404914.0    22966  82.0
French Polynesia                 67.8018    175.6066  282530.0     4167  60.0
Guadeloupe                      245.7125    636.3955  400020.0     1628  53.0
United States Virgin Islands    300.3631    777.9405  104226.0      347  29.0

### 10-VAZIFA. Quyidagi davlatlarning `aholi` sonini oddiy son ko'rinishida chiqaring:
- `Malaysia`
- `Nigeria`
- `Nepal`
- `Italy`

In [ ]:
# JAVOBNI SHUYERGA YOZING

In [ ]:
#@title o'xshash natija (`Uzbekistan` uchun)

33935763.0