In [1]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/refs/heads/main/world_population_duplicates.csv", index_col=1)
df

                  rank     density   densityMi    pop2021     area
country
Macau                1  21946.4667  56841.3487    658.394       30
Monaco               2  19755.5000  51166.7450     39.511        2
Burundi             28    440.3044   1140.3884  12255.433    27834
Macau                1  21946.4667  56841.3487    658.394       30
Monaco               2  19755.5000  51166.7450     39.511        2
...                ...         ...         ...        ...      ...
Namibia            228      3.1338      8.1166   2587.344   825615
Western Sahara     229      2.3003      5.9577    611.875   266000
Mongolia           230      2.1286      5.5129   3329.289  1564110
Falkland Islands   231      0.2902      0.7517      3.533    12173
Greenland          232      0.0263      0.0680     56.877  2166086

[247 rows x 5 columns]

In [5]:
df.loc['Uzbekistan']

rank            133.0000
density          75.8511
densityMi       196.4542
pop2021       33935.7630
area         447400.0000
Name: Uzbekistan, dtype: float64

In [6]:
df.loc['India']

rank         2.900000e+01
density      4.238391e+02
densityMi    1.097743e+03
pop2021      1.393409e+06
area         3.287590e+06
Name: India, dtype: float64

In [8]:
bins = [0,1000,10000,30000,50000,100000,300000,1500000]

In [9]:
population = df.pop2021
population

country
Macau                 658.394
Monaco                 39.511
Burundi             12255.433
Macau                 658.394
Monaco                 39.511
                      ...
Namibia              2587.344
Western Sahara        611.875
Mongolia             3329.289
Falkland Islands        3.533
Greenland              56.877
Name: pop2021, Length: 247, dtype: float64

In [10]:
group = pd.cut(population, bins)
group

country
Macau                    (0, 1000]
Monaco                   (0, 1000]
Burundi             (10000, 30000]
Macau                    (0, 1000]
Monaco                   (0, 1000]
                         ...
Namibia              (1000, 10000]
Western Sahara           (0, 1000]
Mongolia             (1000, 10000]
Falkland Islands         (0, 1000]
Greenland                (0, 1000]
Name: pop2021, Length: 247, dtype: category
Categories (7, interval[int64, right]): [(0, 1000] < (1000, 10000] < (10000, 30000] <
                                         (30000, 50000] < (50000, 100000] < (100000, 300000] <
                                         (300000, 1500000]]

In [11]:
guruh = group.value_counts()
guruh

pop2021
(0, 1000]            80
(1000, 10000]        73
(10000, 30000]       46
(30000, 50000]       19
(50000, 100000]      15
(100000, 300000]     11
(300000, 1500000]     3
Name: count, dtype: int64

In [13]:
df['guruh'] = group
df

,rank,density,densityMi,pop2021,area,guruh
country,,,,,,
Macau,1,21946.4667,56841.3487,658.394,30,"(0, 1000]"
Monaco,2,19755.5000,51166.7450,39.511,2,"(0, 1000]"
Burundi,28,440.3044,1140.3884,12255.433,27834,"(10000, 30000]"
Macau,1,21946.4667,56841.3487,658.394,30,"(0, 1000]"
Monaco,2,19755.5000,51166.7450,39.511,2,"(0, 1000]"
...,...,...,...,...,...,...
Namibia,228,3.1338,8.1166,2587.344,825615,"(1000, 10000]"
Western Sahara,229,2.3003,5.9577,611.875,266000,"(0, 1000]"
Mongolia,230,2.1286,5.5129,3329.289,1564110,"(1000, 10000]"
Falkland Islands,231,0.2902,0.7517,3.533,12173,"(0, 1000]"
Greenland,232,0.0263,0.0680,56.877,2166086,"(0, 1000]"

In [14]:
df2 = pd.read_csv("https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/automobile_data.csv", index_col=0)
df2

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,13495.0
1,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,16500.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154,19,16500.0
3,audi,sedan,99.8,176.6,ohc,four,102,24,13950.0
4,audi,sedan,99.4,176.6,ohc,five,115,18,17450.0
...,...,...,...,...,...,...,...,...,...
81,volkswagen,sedan,97.3,171.7,ohc,four,85,27,7975.0
82,volkswagen,sedan,97.3,171.7,ohc,four,52,37,7995.0
86,volkswagen,sedan,97.3,171.7,ohc,four,100,26,9995.0
87,volvo,sedan,104.3,188.8,ohc,four,114,23,12940.0
88,volvo,wagon,104.3,188.8,ohc,four,114,23,13415.0

In [17]:
df2.price.describe()

count       58.000000
mean     15387.000000
std      11320.259841
min       5151.000000
25%       6808.500000
50%      11095.000000
75%      18120.500000
max      45400.000000
Name: price, dtype: float64

In [19]:
bins = [0,10000,20000,50000]
range = pd.cut(df2.price, bins)
range

index
0     (10000, 20000]
1     (10000, 20000]
2     (10000, 20000]
3     (10000, 20000]
4     (10000, 20000]
           ...
81        (0, 10000]
82        (0, 10000]
86        (0, 10000]
87    (10000, 20000]
88    (10000, 20000]
Name: price, Length: 61, dtype: category
Categories (3, interval[int64, right]): [(0, 10000] < (10000, 20000] < (20000, 50000]]

In [20]:
range.value_counts()

price
(0, 10000]        28
(10000, 20000]    17
(20000, 50000]    13
Name: count, dtype: int64

In [21]:
names = ['arzon', 'o\'rta', 'qimmat']
range = pd.cut(df2.price, bins, labels=names)
range

index
0     o'rta
1     o'rta
2     o'rta
3     o'rta
4     o'rta
      ...
81    arzon
82    arzon
86    arzon
87    o'rta
88    o'rta
Name: price, Length: 61, dtype: category
Categories (3, object): ['arzon' < 'o'rta' < 'qimmat']

In [22]:
range.value_counts()

price
arzon     28
o'rta     17
qimmat    13
Name: count, dtype: int64

In [24]:
range = pd.cut(df2.price, 3, labels=names)
range

index
0     arzon
1     arzon
2     arzon
3     arzon
4     arzon
      ...
81    arzon
82    arzon
86    arzon
87    arzon
88    arzon
Name: price, Length: 61, dtype: category
Categories (3, object): ['arzon' < 'o'rta' < 'qimmat']

In [26]:
range.value_counts()

price
arzon     44
qimmat     9
o'rta      5
Name: count, dtype: int64

In [27]:
range = pd.qcut(df2.price, 3, labels=names)
range

index
0      o'rta
1     qimmat
2     qimmat
3      o'rta
4     qimmat
       ...
81     o'rta
82     o'rta
86     o'rta
87     o'rta
88     o'rta
Name: price, Length: 61, dtype: category
Categories (3, object): ['arzon' < 'o'rta' < 'qimmat']

In [29]:
range.value_counts()

price
qimmat    20
arzon     19
o'rta     19
Name: count, dtype: int64